package com.barathiraja.jk.gym

import android.annotation.SuppressLint
import android.content.Context
import androidx.credentials.ClearCredentialStateRequest
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await

/** Google sign-in through Credential Manager, then Firebase Auth. */
class AuthRepo(private val app: Context) {
    private val auth = FirebaseAuth.getInstance()

    val user: Flow<FirebaseUser?> = callbackFlow {
        val listener = FirebaseAuth.AuthStateListener { trySend(it.currentUser) }
        auth.addAuthStateListener(listener)
        awaitClose { auth.removeAuthStateListener(listener) }
    }

    val current: FirebaseUser? get() = auth.currentUser

    /** [activity] must be an Activity context: the Google account sheet is shown over it. */
    suspend fun signIn(activity: Context): FirebaseUser {
        val option = GetSignInWithGoogleOption.Builder(webClientId()).build()
        val request = GetCredentialRequest.Builder().addCredentialOption(option).build()
        val credential = CredentialManager.create(activity).getCredential(activity, request).credential
        check(credential is CustomCredential && credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
            "Google didn't return an account"
        }
        val token = GoogleIdTokenCredential.createFrom(credential.data).idToken
        return auth.signInWithCredential(GoogleAuthProvider.getCredential(token, null)).await().user
            ?: error("Sign-in failed")
    }

    suspend fun signOut() {
        auth.signOut()
        runCatching { CredentialManager.create(app).clearCredentialState(ClearCredentialStateRequest()) }
    }

    // Generated by the google-services plugin from google-services.json; looked up by name so the app
    // still compiles before Firebase is set up.
    @SuppressLint("DiscouragedApi")
    private fun webClientId(): String {
        val id = app.resources.getIdentifier("default_web_client_id", "string", app.packageName)
        check(id != 0) { "Google sign-in isn't enabled in Firebase yet" }
        return app.getString(id)
    }
}
